# Generated by Django 5.1.7 on 2025-05-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_rename_is_now_newsunit_is_show_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsunit',
            old_name='put_date',
            new_name='pub_date',
        ),
    ]
