# Generated by Django 5.1.7 on 2025-05-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_put_date_newsunit_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsunit',
            old_name='context',
            new_name='content',
        ),
    ]
